### ISSUE TITLE
Package new version?

### ISSUE THREAD

**Issue by ChALkeR** [ForbesLindesay/cmd-shim#15]
#14 was a pretty important change, and there was still no new version released since that PR got merged.

See https://github.com/nodejs/node/pull/5097#issuecomment-180260055.

**Comment by thefourtheye** [comment]
Oh yes. There should have been a patch release.

**Comment by thefourtheye** [comment]
@ForbesLindesay I think #4 and #12 are backward-compatible bug fixes and #14 is a backward compatible dependency upgrade (there was no API change in graceful-fs). I don't have permissions to publish in npm. Can you release a patch version please?

**Comment by TheAlphaNerd** [comment]
What is the status of this?

ping @othiym23 @iarna @zkat

**Comment by ForbesLindesay** [comment]
Done. I've also added:

 - @isaacs 
 - @othiym23 
 - @thefourtheye 
 - @SkyLined 

as owners on npm.

**Comment by thefourtheye** [comment]
@ForbesLindesay Thanks man :-)
